version: '3.9'

services:

  db:
    image: postgres:11-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "md5"
    healthcheck:
      test: ["CMD-SHELL", "psql postgresql://$(cat /run/secrets/db_user):$(cat /run/secrets/db_passwd)@db:5432/${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./init-user-db.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
      - db-volume:/var/lib/postgresql/data
    secrets:
      - db_passwd
      - db_user

  server:
    image: myserver:v5.0
    env_file:
      - .env
    ports:
      - "58080:58080"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-volume:
    name: "db-volume"

secrets:
  db_passwd:
    file: db_passwd.txt
  db_user: 
    file: db_user.txt