---
# tasks file for ansible-role-docker
- include_tasks: setup-REDOS.yml
  when: ansible_facts['os_family'] == "RED"

- name: Configure Docker daemon options
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: restart docker

- name: Check if /etc/docker is present
  block:

    - name: Get info about dir
      stat:
        path: /etc/docker
      register: directory_check

    - name: /etc/docker exists
      debug:
        msg: "{{ 'The directory exists' if directory_check.stat.exists else 'The directory does not exist' }}"

- name: Trigger all handlers
  meta: flush_handlers

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"