---
- hosts: all
  roles:
    - role: ansible-role-firewall
      tags: [ setup, firewall, deploy ]

    - role: ansible-role-docker
      tags: [ setup, docker, deploy ]

  tasks:
    - name: Deploy all
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: present
        recreate: always
      tags: [ deploy ]
      register: output

    - name: Destroy all
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: absent
        remove_volumes: "{{ manage_volumes_destroy }}"
      tags: [ destroy ]
      register: output

    - name: Show results
      debug:
        var: output
      tags: always

- hosts: db_server
  tasks:
    - name: Deploy postgres
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        service: db
        state: present
        recreate: always
      tags: [ deploy_infra, deploy_db, deploy ]
      register: output

    - name: Destroy postgres
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        service: db
        state: absent
      tags: [ destroy_infra, destroy_db, destroy ]
      register: output

    - name: Show results
      debug:
        var: output
      tags: always

- hosts: web_server
  tasks:
    - name: Build image
      community.docker.docker_image:
        build:
          path: "{{ image_path }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        state: "{{ image_state }}"
      tags: [ build_web, deploy_web, deploy]
      register: output

    - name: Deploy web
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: present
        recreate: always
        service: server
      tags: [ deploy_web, deploy ]
      register: output

    - name: Destroy web
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        service: server
        state: absent
      tags: [ destroy_web, destroy ]
      register: output

    - name: Show results
      debug:
        var: output
      tags: always