---
- hosts: all
  roles:
    - role: ansible-role-firewall
      tags: [ setup, firewall ]

    - role: ansible-role-docker
      tags: [ setup, docker ]

  tasks:
    - name: Deploy all
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: present
        recreate: always
      tags: [ deploy ]

    - name: Destroy all
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: absent
        remove_volumes: "{{ manage_volumes_destroy }}"
      tags: [ destroy ]

- hosts: db_server
  tasks:
    - name: Deploy postgres
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        services: db
        state: present
        recreate: always
      tags: [ deploy_infra, deploy_db, deploy ]

    - name: Destroy postgres
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        services: db
        state: absent
      tags: [ destroy_infra, destroy_db, destroy ]

- hosts: web_server
  tasks:
    - name: Build image
      community.docker.docker_image:
        build:
          path: "{{ image_path }}"
        name: "myserver"
        tag: "{{ image_tag }}"
        source: build
        state: "{{ image_state }}"
      tags: [ build_web ]

    - name: Update Docker image version
      ansible.builtin.replace:
        regexp: '^(\s*image:\s*myserver:)(v[0-9]+\.[0-9]+)'
        replace: '\1{{ image_tag }}'
        path: "{{ docker_compose_path }}/docker-compose.yml"
      tags: [ build_web ]

    - name: Deploy web
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: present
        recreate: always
        services: server
      tags: [ deploy_web, deploy ]

    - name: Destroy web
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        services: server
        state: absent
      tags: [ destroy_web, destroy ]